#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:

### Update operating system packages.
sudo apt-get -y update
### Install nginx.
sudo apt-get -y install nginx
### Change de defaul content of index.html for nginx.
echo "Hello World" > index.html
# send the file to new directory
sudo mv index.html /var/www/html
### Start service nginx.
sudo service nginx start