#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:
# Install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' #on port 80
echo "Hello World!" >/var/www/html/index.nginx-debian.html
service nginx restart