#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #on port 80
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sed -i '46i rewrite ^/redirect_me https://www.nginx.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
