#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements




### Update operating system packages.
sudo apt-get -y update
### Install nginx.
sudo apt-get -y install nginx
### Can you try explicitly allowing Nginx HTTPS as well with this command
ufw allow 'Nginx HTTP'
### Start the service 
sudo service nginx start
### Change de defaul content of index.html for nginx.
echo 'Hello World' > /var/www/html/index.nginx-debian.html
### The redirection must be a “301 Moved Permanently”.
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

### Start service nginx.
sudo service nginx restart
### Reload service nginx.
sudo service nginx reload