#!/usr/bin/env bash
# configure HAproxy loadbalancer wit roundrobin

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen juanposada \n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 3895-web-01 34.148.148.119:80 check\n\tserver 3895-web-02 3.90.180.243:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start