#!/usr/bin/env bash
# configure HAproxy loadbalancer wit roundrobin

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen diegojojoa \n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 3922-web-01 52.90.59.238:80 check\n\tserver 3922-web-02 54.197.203.132:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start