#!/usr/bin/env bash
# We stopped our 4-to_inifinity_and_beyond process using ctrl+c in the previous task.
# Write a bash scrip that stops 4 to infiniy and  beyond  process.
kill "$(pgrep -f "4-to_infinity_and_beyond")"
