#!/usr/bin/env bash
# Write in console Best School 10 times, but for the 9th print "Hi"
LIMIT=10
i=1
while [ "$i" -le "$LIMIT" ]
do
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
	((i+=1))
done
